### ISSUE TITLE
stopped working, here's why

### ISSUE THREAD

**Issue by ghost** [akilan27/footab#1]
You mentioned in the readme that it stopped working, this is why:
https://chromium.googlesource.com/chromium/src/+/5ff4eeaefbc41f51d02887e0c42bb6e72ba292a0

**Comment by ghost** [comment]
You might be interested to know, there is a replacement for footab, a minimal extension [Sloth](https://github.com/hrj/sloth) that uses discard API similar to what `chrome://discards` does.

**Comment by akilangh** [comment]
Ok. Thanks for pointing this out. I gave up after a while when I couldn't find any issue with the code but it didn't work anyway. I will add link to Sloth in Readme.
